[package]

name = "clipboard"
version = "0.1.1"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
description = "rust-clipboard is a cross-platform library for getting and setting the contents of the OS-level clipboard."
repository = "https://github.com/aweinstock314/rust-clipboard"
license = "Apache-2.0/GPL-2.0"
keywords = ["clipboard"]

[target.i686-pc-windows-gnu.dependencies]
clipboard-win = "1.5.1"

[target.x86_64-pc-windows-gnu.dependencies]
clipboard-win = "1.5.1"

[target.i686-apple-darwin.dependencies]
objc = "0.1.8"
objc_id = "0.0.2"
objc-foundation = "0.0.4"

[target.x86_64-apple-darwin.dependencies]
objc = "0.1.8"
objc_id = "0.0.2"
objc-foundation = "0.0.4"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "2.3.0"
features = ["xlib", "xmu"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "2.3.0"
features = ["xlib", "xmu"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "2.3.0"
features = ["xlib", "xmu"]

[target.aarch64-unknown-linux-gnu.dependencies.x11]
version = "2.3.0"
features = ["xlib", "xmu"]
