[package]

name = "clipboard"
version = "0.0.1"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
libc = "*"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib", "xmu"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib", "xmu"]

[target.arm-unknown-linux-gnueabihf.dependencies.x11]
version = "1.1.1"
features = ["xlib", "xmu"]
