[package]
name = "arboard"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>", "Artur Kovacs <kovacs.artur.barnabas@gmail.com>"]
description = "Getting and setting text and image for the OS-level clipboard."
repository = "https://github.com/ArturKovacs/arboard"
license = "MIT / Apache-2.0"
keywords = ["clipboard"]

[target.'cfg(windows)'.dependencies]
clipboard-win = "3.0"
image = { version = "0.23", default-features = false, features = ["bmp"] }
byteorder = "1.3"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
objc_id = "0.1"
objc-foundation = "0.1"
image = { version = "0.23", default-features = false, features = ["tiff"] }

[target.'cfg(all(unix, not(any(target_os="macos", target_os="android", target_os="emscripten"))))'.dependencies]
xcb = "0.9"
lazy_static = "1.4.0"
libc = "0.2"
image = { version = "0.23", default-features = false, features = ["png"] }
